### ISSUE TITLE
train_test_split only accepts dask arrays

### ISSUE THREAD

**Issue by stsievert** [dask/dask-ml#215]
Minimal working example:

``` python
from sklearn.datasets import fetch_20newsgroups
import numpy as np
import dask.array as da
import sklearn.model_selection as ms
from dask_ml.model_selection import train_test_split

data = fetch_20newsgroups(subset='train', categories=None)
X, y = data.data, data.target

assert isinstance(X, list)
assert isinstance(X[0], str)
assert isinstance(y, np.ndarray)
assert y.dtype == int

ms.train_test_split(X, y)
train_test_split(X, y)
```

Traceback:

```python-traceback
Traceback (most recent call last):
  File "bug.py", line 19, in <module>
    train_test_split(X, y)
  File "/Users/ssievert/anaconda3/lib/python3.6/site-packages/dask_ml/model_selection/_split.py", line 273, in train_test_split
    assert all(isinstance(arr, da.Array) for arr in arrays)
AssertionError
```

**Comment by TomAugspurger** [comment]
The current implementation relies heavily on knowing the sizes of each block. dask dataframe doesn't know the length of each partition, so we'll have to take a different apporach.

**Comment by stsievert** [comment]
This was mostly a reference for #216. Could you comment there instead?
