### ISSUE TITLE
`toolz` missing from `install_requires`

### ISSUE THREAD

**Issue by noseworthy** [dask/dask-ml#304]
dask-ml requires `toolz` to be installed but it is not listed as a dependency in `setup.py`.

Reproduce:
```bash
$ python -m venv .venv
$ source .venv/bin/activate
$ pip install dask-ml
$ pip install packaging  # because update hasn't been released which adds packaging as a dependency
$ python -c "from dask_ml.model_selection import GridSearchCV"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mike.noseworthy/Development/python-demo/.venv/lib/python3.6/site-packages/dask_ml/model_selection/__init__.py", line 6, in <module>
    from ._search import (
  File "/Users/mike.noseworthy/Development/python-demo/.venv/lib/python3.6/site-packages/dask_ml/model_selection/_search.py", line 12, in <module>
    from dask.base import tokenize
  File "/Users/mike.noseworthy/Development/python-demo/.venv/lib/python3.6/site-packages/dask/base.py", line 14, in <module>
    from toolz import merge, groupby, curry, identity
ModuleNotFoundError: No module named 'toolz'                                                                                                                                                                      
```

**Python Version**: 3.6.5
**Pip Version**: 10.0.1
**Setuptools Version**: 40.0.0
**Wheel Version**: 0.31.1

**Comment by TomAugspurger** [comment]
This was fixed by #305
