### ISSUE TITLE
KMeans Clustering Data Type Error

### ISSUE THREAD

**Issue by QuinnRAndersonDS** [dask/dask-ml#378]
I am attempting to execute the following code.

##############################
from sklearn.datasets import make_blobs
from dask_ml.cluster import KMeans

x, y = make_blobs(n_samples = 100000, n_features = 2)

model = KMeans()

model.fit(x)
##############################

But it generates the following error.

##############################
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 199, in fit
    tol=self.tol,
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 270, in k_means
    init_max_iter=init_max_iter,
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 518, in _kmeans_single_lloyd
    max_iter=init_max_iter,
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 361, in k_init
    return init_scalable(X, n_clusters, random_state, max_iter, oversampling_factor)
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\utils.py", line 334, in wraps
    results = f(*args, **kwargs)
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 459, in init_scalable
    rng2 = random_state.randint(0, 2 ** 32 - 1, chunks=()).compute().item()
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask\array\random.py", line 336, in randint
    size=size, chunks=chunks)
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask\array\random.py", line 122, in _wrap
    **small_kwargs).dtype
  File "mtrand.pyx", line 991, in mtrand.RandomState.randint
ValueError: high is out of bounds for int32

##############################

Python Version 3.7.0
Dask Version 0.19.2
Dask_ml Version 0.10.0
Dask-glm Version 0.1.0

##############################

Thank you

**Comment by TomAugspurger** [comment]
Hrm I thought we fixed all these...

https://github.com/dask/dask-ml/blob/master/dask_ml/cluster/k_means.py#L459 should be 

```
        rng2 = random_state.randint(0, np.iinfo('i4').max, - 1, chunks=()).compute().item()
```

and that compute should probably use the `scheduler='single-threaded'` keyword.

**Comment by TomAugspurger** [comment]
FYI, you can work around this for now my specifying `model=KMeans(random_state=0)` or any integer.

**Comment by QuinnRAndersonDS** [comment]
Thank you for the quick response.  Changing line 459 is resulting in the following error.

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 199, in fit
    tol=self.tol,
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 270, in k_means
    init_max_iter=init_max_iter,
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 518, in _kmeans_single_lloyd
    max_iter=init_max_iter,
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 361, in k_init
    return init_scalable(X, n_clusters, random_state, max_iter, oversampling_factor)
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\utils.py", line 334, in wraps
    results = f(*args, **kwargs)
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask_ml\cluster\k_means.py", line 459, in init_scalable
    rng2 = random_state.randint(0, np.iinfo('i4').max, - 1, chunks=()).compute().item()
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask\array\random.py", line 336, in randint
    size=size, chunks=chunks)
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask\array\random.py", line 75, in _wrap
    dtype=kwargs.get('dtype', np.float64))
  File "C:\Users\tl928yx\AppData\Local\Programs\Python\Python37\lib\site-packages\dask\array\core.py", line 2154, in normalize_chunks
    "Got chunks=%s, shape=%s" % (chunks, shape))
ValueError: Chunks and shape must be of the same length/dimension. Got chunks=(), shape=(-1,)

**Comment by TomAugspurger** [comment]
Sorry, typo in my code snippet. Fixed.

**Comment by QuinnRAndersonDS** [comment]
Works!  Thank you!
