### ISSUE TITLE
ImportError: fsspec is required to use any file-system functionality

### ISSUE THREAD

**Issue by AnesBenmerzoug** [dask/dask-ml#537]
On a fresh install of dask-ml, the following snippet:

```python
import dask.array as da
from dask_ml.linear_model import LogisticRegression
from dask_ml.model_selection import train_test_split
from sklearn.datasets import load_iris

if __name__ == "__main__":
    iris = load_iris()
    X, y = iris.data, iris.target
    X, y = da.from_array(X, chunks=len(X) // 5), da.from_array(y, chunks=len(y) // 5)
    classifier = LogisticRegression(max_iter=max_iter, solver=solver, C=C)
    X_train, X_test, y_train, y_test = train_test_split(X, y)
    classifier.fit(X_train, y_train)
    score = classifier.score(X_test, y_test)
```

gives the error:

```python
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from dask_ml.linear_model import LogisticRegression
  File "/home/koutetsu/projects/dask-ml-fsspec-error/venv/lib/python3.6/site-packages/dask_ml/linear_model/__init__.py", line 4, in <module>
    from .glm import LinearRegression, LogisticRegression, PoissonRegression
  File "/home/koutetsu/projects/dask-ml-fsspec-error/venv/lib/python3.6/site-packages/dask_ml/linear_model/glm.py", line 17, in <module>
    from ..utils import check_array
  File "/home/koutetsu/projects/dask-ml-fsspec-error/venv/lib/python3.6/site-packages/dask_ml/utils.py", line 12, in <module>
    import dask.dataframe as dd
  File "/home/koutetsu/projects/dask-ml-fsspec-error/venv/lib/python3.6/site-packages/dask/dataframe/__init__.py", line 57, in <module>
    raise ImportError(str(e) + "\n\n" + msg)
ImportError: fsspec is required to use any file-system functionality. Please install using
conda install -c conda-forge 'fsspec>=0.3.3'
or
pip install 'fsspec>=0.3.3'
```

Checking the [requirements](https://github.com/dask/dask-ml/blob/master/setup.py#L13-L24) of dask-ml shows that only array extras are install and that installing the dataframe extras in addition to that would solve this error

**Comment by jrbourbeau** [comment]
Dask added `fsspec` as a dependency in version `2.2.0`. Installing `fsspec` should hopefully fix the issue you're seeing

**Comment by AnesBenmerzoug** [comment]
Should ```fsspec``` or ```dask[dataframe]``` be listed as a requirement for ```dask-ml``` then?
Since simply importing one of ```LinearRegression, LogisticRegression, PoissonRegression``` would raise the error if one only install ```dask-ml```

**Comment by TomAugspurger** [comment]
We can add dataframe to the dask.array extra.
