### ISSUE TITLE
PCA ParallelPostFit.transform fails with scikit-learn=0.24.0

### ISSUE THREAD

**Issue by abduhbm** [dask/dask-ml#773]
**What happened**:
PCA.transform with ParallelPost fails when running with scikit-learn=0.24.0

**Minimal Complete Verifiable Example**:

```python
X, y = make_classification(n_samples=1_000, n_features=10, 
                           random_state=0, chunks=100)
clf = ParallelPostFit(estimator=PCA(random_state=0))
clf.fit(*dask.compute(X, y))
clf.transform(X)
---------------------------------------------------------------------------
ValueError('X has 1 features, but PCA is expecting 10 features as input.')
```

**Anything else we need to know?**:
It looks like the `reset` flag in `_validate_data` is causing this error.  
https://github.com/scikit-learn/scikit-learn/blob/cbfe0ede80beca86750ab8113f17c18c8c8042ce/sklearn/decomposition/_base.py#L126

**Environment**:

- Dask version: 2020.12.0
- Python version: 3.7.6
- Operating System: MacOS
- Install method (conda, pip, source): pip

**Comment by abduhbm** [comment]
Calling `transform` for PCA in ParallelPost wrapper without the `_validate_data` check resolved this issue ... not sure if this is a right approach to fix this. 

https://github.com/dask/dask-ml/blob/976761ffcd89a6d370b5a29e61d7e80dd5bdd317/dask_ml/wrappers.py#L551-L552

Something like: 
```python
def _transform(part, estimator):
    if type(estimator) == sklearn.decomposition.PCA:
        check_is_fitted(estimator)
        if estimator.mean_ is not None:
            part = part - estimator.mean_
        part_transformed = np.dot(part, estimator.components_.T)
        if estimator.whiten:
            part_transformed /= np.sqrt(estimator.explained_variance_)
        return part_transformed

    return estimator.transform(part)
```

**Comment by TomAugspurger** [comment]
Thanks for the report. Can you include the full traceback? I see something different

```pytb
In [9]: X, y = make_classification(n_samples=1_000, n_features=10,
   ...:                            random_state=0, chunks=100)
   ...: clf = ParallelPostFit(estimator=PCA(random_state=0))
   ...: clf.fit(*dask.compute(X, y))
   ...: clf.transform(X)
   ...:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-b90baaf11b6c> in <module>
      3 clf = ParallelPostFit(estimator=PCA(random_state=0))
      4 clf.fit(*dask.compute(X, y))
----> 5 clf.transform(X)

/usr/local/Caskroom/miniconda/base/envs/sk024/lib/python3.8/site-packages/dask_ml/wrappers.py in transform(self, X)
    205
    206         if isinstance(X, da.Array):
--> 207             return X.map_blocks(_transform, estimator=self._postfit_estimator)
    208         elif isinstance(X, dd._Frame):
    209             return X.map_partitions(_transform, estimator=self._postfit_estimator)

/usr/local/Caskroom/miniconda/base/envs/sk024/lib/python3.8/site-packages/dask/array/core.py in map_blocks(self, func, *args, **kwargs)
   2240     @wraps(map_blocks)
   2241     def map_blocks(self, func, *args, **kwargs):
-> 2242         return map_blocks(func, self, *args, **kwargs)
   2243
   2244     def map_overlap(self, func, depth, boundary=None, trim=True, **kwargs):

/usr/local/Caskroom/miniconda/base/envs/sk024/lib/python3.8/site-packages/dask/array/core.py in map_blocks(func, name, token, dtype, chunks, drop_axis, new_axis, meta, *args, **kwargs)
    668             pass
    669
--> 670         dtype = apply_infer_dtype(func, args, original_kwargs, "map_blocks")
    671
    672     if drop_axis:

/usr/local/Caskroom/miniconda/base/envs/sk024/lib/python3.8/site-packages/dask/array/core.py in apply_infer_dtype(func, args, kwargs, funcname, suggest_dtype, nout)
    403         msg = None
    404     if msg is not None:
--> 405         raise ValueError(msg)
    406     return o.dtype if nout is None else tuple(e.dtype for e in o)
    407

ValueError: `dtype` inference failed in `map_blocks`.

Please specify the dtype explicitly using the `dtype` kwarg.

Original error is below:
------------------------
ValueError('X has 1 features, but PCA is expecting 10 features as input.')

Traceback:
---------
  File "/usr/local/Caskroom/miniconda/base/envs/sk024/lib/python3.8/site-packages/dask/array/core.py", line 380, in apply_infer_dtype
    o = func(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/envs/sk024/lib/python3.8/site-packages/dask_ml/wrappers.py", line 552, in _transform
    return estimator.transform(part)
  File "/usr/local/Caskroom/miniconda/base/envs/sk024/lib/python3.8/site-packages/sklearn/decomposition/_base.py", line 126, in transform
    X = self._validate_data(X, dtype=[np.float64, np.float32], reset=False)
  File "/usr/local/Caskroom/miniconda/base/envs/sk024/lib/python3.8/site-packages/sklearn/base.py", line 437, in _validate_data
    self._check_n_features(X, reset=reset)
  File "/usr/local/Caskroom/miniconda/base/envs/sk024/lib/python3.8/site-packages/sklearn/base.py", line 365, in _check_n_features
    raise ValueError(
```

**Comment by TomAugspurger** [comment]
So the failure is in dtype inference for the output. By default, dask makes a `(1, 1)` array for a 2-d input. But the function passed here depends on the output.

So I think dask-ml should take over type inference here, by making a dummy array with the right dtype and the right shape along the features. Then call the transformer on that and extract the output, to pass through to the `map_blocks` call. Are you interested in working on that @abduhbm?

**Comment by abduhbm** [comment]
Thanks @TomAugspurger for the clarification. I created a PR for this.
